# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
local    all             all                            trust
host     all             replicator            all        scram-sha-256
host     all             postgres       all        scram-sha-256
host     all             all                all         scram-sha-256
